exclude: '.*.html$'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-json
    types: [text]
    files: \.(json|jsonld)$
  - id: check-toml
  - id: check-yaml
  - id: check-ast
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=21500']
  - id: detect-private-key
  - id: end-of-file-fixer
    files: ".*\\.py$"
  - id: requirements-txt-fixer
  - id: name-tests-test
  - id: pretty-format-json
    types: [text]
    files: \.(json|jsonld)$
    args: ['--autofix']
  - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: remove-tabs
    exclude_types: [makefile, batch]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --preserve-quotes]
  - id: pretty-format-toml
    args: [--autofix]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
  - id: ruff-format
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
- repo: https://github.com/asottile/pyupgrade
  rev: v3.17.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.4.20
  hooks:
  - id: pip-compile
    args: [pyproject.toml, --output-file, requirements.txt, --python-version, "3.12"]
    files: ^pyproject.toml$
